"""Generate the MkDocs reference pages from the live catalogs.

Run from the backend dir:

    .venv/bin/python scripts/gen_docs.py

Writes ``docs/reference/{operators,fields,cookbook}.md`` at the repo root. These
pages are DERIVED FROM CODE so they can't drift from the real operator/field
set: CI regenerates them and fails if the committed copy differs (see the
``docs`` job in .github/workflows/ci.yml). Output is deterministic — no
timestamps — so an unchanged catalog produces a byte-identical file.
"""

from __future__ import annotations

import sys
from pathlib import Path

_BACKEND = Path(__file__).resolve().parents[1]
_REPO = _BACKEND.parent
if str(_BACKEND) not in sys.path:
    sys.path.insert(0, str(_BACKEND))

from data.example_alphas import list_examples  # noqa: E402
from data.fundamentals import ALL_FUNDAMENTAL_FIELDS  # noqa: E402
from data.macro import DERIVED_MACRO_BUILDERS, FRED_SERIES  # noqa: E402
from data.universes import GICS_LEVELS  # noqa: E402
from main import FIELDS, OPERATORS  # noqa: E402

_DOCS = _REPO / "docs" / "reference"
_AUTOGEN = "<!-- AUTO-GENERATED by backend/scripts/gen_docs.py — do not edit by hand. -->"


def _title(key: str) -> str:
    return key.replace("_", " ").strip().capitalize()


def _cell(s: str) -> str:
    """Escape a string for a Markdown table cell."""
    return str(s).replace("|", "\\|").replace("\n", " ").strip()


def _group_ordered(items, key):
    """Group dicts by a key, preserving first-seen category order."""
    out: dict[str, list] = {}
    for it in items:
        out.setdefault(it[key], []).append(it)
    return out


def gen_operators() -> str:
    lines = [
        "# Operator reference",
        "",
        _AUTOGEN,
        "",
        f"QuantLab's alpha DSL provides **{len(OPERATORS)} operators**. They compose "
        "freely with data fields and arithmetic (`+ - * /`, unary `-`). `x` is a "
        "`(dates × tickers)` matrix; `d` is an integer lookback in trading days.",
        "",
    ]
    for cat, ops in _group_ordered(OPERATORS, "category").items():
        lines += [
            f"## {_title(cat)}",
            "",
            "| Operator | Signature | Description |",
            "| --- | --- | --- |",
        ]
        for op in ops:
            lines.append(f"| `{op['name']}` | `{_cell(op['args'])}` | {_cell(op['description'])} |")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def gen_fields() -> str:
    lines = [
        "# Field reference",
        "",
        _AUTOGEN,
        "",
        "Data fields are the leaves of an alpha expression. Price/volume and derived "
        "fields are always available; fundamentals, macro, and GICS grouping fields "
        "depend on the deployment's data coverage.",
        "",
    ]
    # Price + derived (rich descriptions live in the FIELDS catalog).
    for cat, fields in _group_ordered(FIELDS, "category").items():
        lines += [f"## {_title(cat)}", "", "| Field | Description |", "| --- | --- |"]
        for f in fields:
            lines.append(f"| `{f['name']}` | {_cell(f['description'])} |")
        lines.append("")
    # Fundamentals (names only — availability + values depend on yfinance coverage).
    lines += [
        "## Fundamentals",
        "",
        "Lagged ~1 quarter as a point-in-time proxy. Availability depends on the "
        "deployment's fundamentals coverage.",
        "",
        ", ".join(f"`{name}`" for name in ALL_FUNDAMENTAL_FIELDS),
        "",
    ]
    # Macro (FRED-derived), with descriptions.
    lines += ["## Macro", "", "| Field | Description |", "| --- | --- |"]
    for name, (_code, desc) in FRED_SERIES.items():
        lines.append(f"| `{name}` | {_cell(desc)} |")
    for name, formula in DERIVED_MACRO_BUILDERS:
        lines.append(f"| `{name}` | Derived: `{_cell(formula)}` |")
    lines.append("")
    # GICS grouping levels (categorical — feed the group_* operators).
    lines += [
        "## Sector / industry grouping",
        "",
        "Categorical fields passed as the grouping argument to the `group_*` "
        "operators (e.g. `group_neutralize(x, sector)`):",
        "",
        ", ".join(f"`{lvl}`" for lvl in GICS_LEVELS),
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def gen_cookbook() -> str:
    examples = list_examples()
    lines = [
        "# Alpha cookbook",
        "",
        _AUTOGEN,
        "",
        f"**{len(examples)} starter alphas**, each a complete, valid expression with "
        "recommended settings. Load any of them from the editor's *Load Example* menu.",
        "",
    ]
    for cat, items in _group_ordered(examples, "category").items():
        lines += [f"## {cat}", ""]
        for e in items:
            settings = ", ".join(
                f"`{k}={v}`" for k, v in (e.get("recommended_settings") or {}).items()
            )
            teaches = ", ".join(e.get("teaches") or [])
            lines += [
                f"### {e['name']}",
                "",
                "```",
                e["expression"],
                "```",
                "",
                e["description"],
                "",
            ]
            if teaches:
                lines += [f"**Teaches:** {teaches}", ""]
            if settings:
                lines += [f"**Recommended settings:** {settings}", ""]
    return "\n".join(lines).rstrip() + "\n"


def main() -> None:
    _DOCS.mkdir(parents=True, exist_ok=True)
    pages = {
        "operators.md": gen_operators(),
        "fields.md": gen_fields(),
        "cookbook.md": gen_cookbook(),
    }
    for name, content in pages.items():
        (_DOCS / name).write_text(content, encoding="utf-8")
        print(f"wrote docs/reference/{name} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
